### DISCUSSION TITLE
field contents not found in type nfpm.Config

### DISCUSSION THREAD

**Discussion by GaikwadPratik** [goreleaser/nfpm#343] [Q&A] [answered]
@caarlos0,
I'm trying to build a Debian package using nfpm. I did successfully in the past but today all of sudden I started having issues.
Here is my nfpm.yaml

```
# nfpm example config file
#
# check https://nfpm.goreleaser.com/configuration for detailed usage
#
name: "hive-vm-manager"
arch: "amd64"
platform: "linux"
version: "v1.0.0"
section: "default"
priority: "extra"
depends:
#- libvirtd
- rethinkdb
maintainer: "Pratik Gaikwad <pratik.gaikwad@hiveio.com>"
description: |
  Hive-vm-manager deals with libvirt and bindings can be invoked over dbus
vendor: "Hive IO"
homepage: "http://hiveio.com"
license: "MIT"
changelog: debian/changelog
contents:
  - src: dist/hive-vm-manager_linux_amd64/hio-vm-manager
    dst: /opt/hive/services/hive-vm-manager/hio-vm-manager
    file_info:
      mode: 0700
      owner: root
      group: root
  - src: files/systemd/hive-vm-manager.service
    dst: /lib/systemd/system/hive-vm-manager.service
    type: config
  - src: /opt/hive/services/hive-vm-manager/hio-vm-manager
    dst: /opt/hive/bin/hio-vm-manager
    type: symlink
deb:
  scripts:
    rules: debian/rules
```

When I run `mkdir -p bin/ && nfpm pkg --packager deb --target bin/`, I keep getting:
```
nfpm: error: yaml: unmarshal errors:
  line 21: field contents not found in type nfpm.Config
```

I'm using that inside a docker, if that makes any difference
