### DISCUSSION TITLE
field posttrans not found in type nfpm.Overridables

### DISCUSSION THREAD

**Discussion by flynn1973** [goreleaser/nfpm#355] [Q&A] [answered]
got the following error, read somewhere that posttrans is not a problem...whats wrong?

````
root@lpgaixmgmtlx01:/scratch/go/dev/src/github.com/grafana/grafana/packaging/conf>/scratch/go/dev/bin/nfpm -v
nfpm version nfpm version dev
module version: v2.6.0, checksum: h1:bwDU9o4/CVTSpqASJA7+r+rkqpTGamQKYHMRH3wDlRE=
````

````
root@lpgaixmgmtlx01:/scratch/go/dev/src/github.com/grafana/grafana/packaging/conf>/scratch/go/dev/bin/nfpm pkg --packager rpm --target /tmp/
yaml: unmarshal errors:
  line 47: field posttrans not found in type nfpm.Overridables
````
nfpm.yaml
````
name: "grafana"
arch: "ppc64le"
platform: "linux"
version: "8.0.5"
section: "default"
priority: "extra"
replaces:
- grafana
provides:
- grafana-server
- grafana-cli
depends:
- adduser
- libfontconfig1
maintainer: "<contact@grafana.com>"
description: |
  Grafana
vendor: "Grafana"
homepage: "https://grafana.com"
license: "Apache 2"
contents:
        - src: /scratch/go/dev/src/github.com/grafana/grafana/bin/linux-ppc64le/grafana-server
          dst: /usr/sbin/grafana-server
        - src: /scratch/go/dev/src/github.com/grafana/grafana/bin/linux-ppc64le/grafana-cli
          dst: /usr/sbin/grafana-cli
        - src: /scratch/go/dev/src/github.com/grafana/grafana/packaging/rpm/init.d/grafana-server
          dst: /etc/init.d/grafana-server
        - src: /scratch/go/dev/src/github.com/grafana/grafana/packaging/rpm/sysconfig/grafana-server
          dst: /etc/sysconfig/grafana-server
          type: config|noreplace
        - src: /scratch/go/dev/src/github.com/grafana/grafana/packaging/rpm/systemd/grafana-server.service
          dst: /usr/lib/systemd/system/grafana-server.service
        - src: /scratch/go/dev/src/github.com/grafana/grafana/public/
          dst: /usr/share/grafana/public
        - src: /scratch/go/dev/src/github.com/grafana/grafana/conf/
          dst: /usr/share/grafana/conf

empty_folders:
  - /etc/grafana

scripts:
    postinstall: /scratch/go/dev/src/github.com/grafana/grafana/packaging/rpm/control/postinst

overrides:
    rpm:
        scripts:
        posttrans: /scratch/go/dev/src/github.com/grafana/grafana/packaging/rpm/control/posttrans

````

**Comment by caarlos0** [comment]
it seems you are missing an indentation level on posttrans...

**Comment by flynn1973** [comment]
removed the overide stuff  and changed it to this, still the same error.

````
scripts:
    postinstall: /scratch/go/dev/src/github.com/grafana/grafana/packaging/rpm/control/postinst
    posttrans: /scratch/go/dev/src/github.com/grafana/grafana/packaging/rpm/control/posttrans
````

**Reply by caarlos0** [reply]
Can you share your full config after the changes? 

PS: please reply on the thread to keep this organized

**Comment by flynn1973** [comment]
````
name: "grafana"
arch: "ppc64le"
platform: "linux"
version: "8.0.5"
section: "default"
priority: "extra"
replaces:
- grafana
provides:
- grafana-server
- grafana-cli
depends:
- adduser
- libfontconfig1
maintainer: "<contact@grafana.com>"
description: |
  Grafana
vendor: "Grafana"
homepage: "https://grafana.com"
license: "Apache 2"
contents:
        - src: /scratch/go/dev/src/github.com/grafana/grafana/bin/linux-ppc64le/grafana-server
          dst: /usr/sbin/grafana-server
        - src: /scratch/go/dev/src/github.com/grafana/grafana/bin/linux-ppc64le/grafana-cli
          dst: /usr/sbin/grafana-cli
        - src: /scratch/go/dev/src/github.com/grafana/grafana/packaging/rpm/init.d/grafana-server
          dst: /etc/init.d/grafana-server
        - src: /scratch/go/dev/src/github.com/grafana/grafana/packaging/rpm/sysconfig/grafana-server
          dst: /etc/sysconfig/grafana-server
          type: config|noreplace
        - src: /scratch/go/dev/src/github.com/grafana/grafana/packaging/rpm/systemd/grafana-server.service
          dst: /usr/lib/systemd/system/grafana-server.service
        - src: /scratch/go/dev/src/github.com/grafana/grafana/public/
          dst: /usr/share/grafana/public
        - src: /scratch/go/dev/src/github.com/grafana/grafana/conf/
          dst: /usr/share/grafana/conf

empty_folders:
  - /etc/grafana

scripts:
    postinstall: /scratch/go/dev/src/github.com/grafana/grafana/packaging/rpm/control/postinst
    posttrans: /scratch/go/dev/src/github.com/grafana/grafana/packaging/rpm/control/posttrans

````

**Reply by caarlos0** [reply]
posttrans does not exist in that level..

```yaml
name: "grafana"
arch: "ppc64le"
platform: "linux"
version: "8.0.5"
section: "default"
priority: "extra"
replaces:
- grafana
provides:
- grafana-server
- grafana-cli
depends:
- adduser
- libfontconfig1
maintainer: "<contact@grafana.com>"
description: |
  Grafana
vendor: "Grafana"
homepage: "https://grafana.com"
license: "Apache 2"
contents:
        - src: /scratch/go/dev/src/github.com/grafana/grafana/bin/linux-ppc64le/grafana-server
          dst: /usr/sbin/grafana-server
        - src: /scratch/go/dev/src/github.com/grafana/grafana/bin/linux-ppc64le/grafana-cli
          dst: /usr/sbin/grafana-cli
        - src: /scratch/go/dev/src/github.com/grafana/grafana/packaging/rpm/init.d/grafana-server
          dst: /etc/init.d/grafana-server
        - src: /scratch/go/dev/src/github.com/grafana/grafana/packaging/rpm/sysconfig/grafana-server
          dst: /etc/sysconfig/grafana-server
          type: config|noreplace
        - src: /scratch/go/dev/src/github.com/grafana/grafana/packaging/rpm/systemd/grafana-server.service
          dst: /usr/lib/systemd/system/grafana-server.service
        - src: /scratch/go/dev/src/github.com/grafana/grafana/public/
          dst: /usr/share/grafana/public
        - src: /scratch/go/dev/src/github.com/grafana/grafana/conf/
          dst: /usr/share/grafana/conf

empty_folders:
  - /etc/grafana

scripts:
    postinstall: /scratch/go/dev/src/github.com/grafana/grafana/packaging/rpm/control/postinst

rpm:
    scripts:
        posttrans: /scratch/go/dev/src/github.com/grafana/grafana/packaging/rpm/control/posttrans

**Comment by caarlos0** [comment, marked as answer]
correct usage would be:

```yaml
name: "grafana"
arch: "ppc64le"
platform: "linux"
version: "8.0.5"
section: "default"
priority: "extra"
replaces:
- grafana
provides:
- grafana-server
- grafana-cli
depends:
- adduser
- libfontconfig1
maintainer: "<contact@grafana.com>"
description: |
  Grafana
vendor: "Grafana"
homepage: "https://grafana.com"
license: "Apache 2"
contents:
        - src: /scratch/go/dev/src/github.com/grafana/grafana/bin/linux-ppc64le/grafana-server
          dst: /usr/sbin/grafana-server
        - src: /scratch/go/dev/src/github.com/grafana/grafana/bin/linux-ppc64le/grafana-cli
          dst: /usr/sbin/grafana-cli
        - src: /scratch/go/dev/src/github.com/grafana/grafana/packaging/rpm/init.d/grafana-server
          dst: /etc/init.d/grafana-server
        - src: /scratch/go/dev/src/github.com/grafana/grafana/packaging/rpm/sysconfig/grafana-server
          dst: /etc/sysconfig/grafana-server
          type: config|noreplace
        - src: /scratch/go/dev/src/github.com/grafana/grafana/packaging/rpm/systemd/grafana-server.service
          dst: /usr/lib/systemd/system/grafana-server.service
        - src: /scratch/go/dev/src/github.com/grafana/grafana/public/
          dst: /usr/share/grafana/public
        - src: /scratch/go/dev/src/github.com/grafana/grafana/conf/
          dst: /usr/share/grafana/conf

empty_folders:
  - /etc/grafana

scripts:
    postinstall: /scratch/go/dev/src/github.com/grafana/grafana/packaging/rpm/control/postinst

rpm:
    scripts:
        posttrans: /scratch/go/dev/src/github.com/grafana/grafana/packaging/rpm/control/posttrans
```
