### DISCUSSION TITLE
debs -- debhelper support?

### DISCUSSION THREAD

**Discussion by insasho** [goreleaser/nfpm#528] [Q&A] [answered]
My project cares only about .deb files. Is there a way to get goreleaser's debs to invoke the standard debhelper scripts so that we can include a .service file in the debian/ directory and have its lifecycle managed automatically? Doing so manually from the postinst/prerm scripts is very error prone and likely to too easily violate deb packaging guidelines.

**Comment by djgilcrease** [comment, marked as answer]
You can just add the service file as part of your package spec.

```yaml
  - src: ./packaging/usr/lib/systemd/system/your.service
    dst: /usr/lib/systemd/system/your.service
    file_info:
      mode: 0644
```

you do not and should not create a .service file as part of the post-install script
