### DISCUSSION TITLE
How to provide alternate depends for distro major versions?

### DISCUSSION THREAD

**Discussion by cognifloyd** [goreleaser/nfpm#650] [Q&A] [answered]
Sometimes package names change between major versions of distros.

My current example is for RPM:
I need `python3-devel` in EL 7, and `python38-devel` in EL 8 (I'm using CentOS 7 and Rocky Linux 8, but the same is true of other RHEL variants).

I've seen this in the past with debian based distros as well, so a generic way to handle this distro major version conditional would be great. Maybe something like:

```yaml
overrides:
  rpm_7:
    depends:
    - python3-devel
  rpm_8:
    depends:
    - python38-devel
```

This would be valid under the jsonschema since overrides uses patternProperties.

Is anything like this planned?
