### DISCUSSION TITLE
The way to make type:tree overwrite another conent entry

### DISCUSSION THREAD

**Discussion by gl1ridae** [goreleaser/nfpm#795] [Q&A]
Hi all,

I wonder how I can achieve one content entry tree type overwrite another. I have the same directories in the trees, but different set of files. So it is conflict only in directory names. 
Example:
```
# dir 1
/tmp/myApp/lib1
|  |-- l1
|  |    |-- one.f
|  |    |-- two.f
|  |    `-- three.f


# dir 2
/tmp/myApp/lib2
|  |-- l1
|  |    |-- four.f
|  |    |-- five.f
|  |    `-- six.f
```
And nfpm exmaple:
```
...
content:
- src: /tmp/myApp/lib1/
  dst: /app/location
  type: tree
- src: /tmp/myApp/lib2/
  dst: /app/location
  type: tree
```

Finally I want to have, without defining file names.
```

/app/location/
|  |-- l1
|  |    |-- one.f
|  |    |-- two.f
|  |    |-- three.f
|  |    |-- four.f
|  |    |-- five.f
|  |    `-- six.f
```

Thank you!
