### ISSUE TITLE
When using `./**/*` for files a 0 byte rpm file gets included in the package

### ISSUE THREAD

**Issue by regner** [goreleaser/nfpm#103]
Sample config:
```yaml
name: "app-name"
arch: "noarch"
platform: "linux"
version: "${APP_VERSION}"
files:
  ./**/* : "/some/location/"
```

Assuming I ran the following command: `nfpm pkg -f sample.yaml -t herpderp.rpm`

When the RPM gets installed I would have a 0 byte file by the name of `herpderp.rpm` in `/some/location/`.

I haven't tested if this happens with .deb as well as we only build .rpm packages.
