### ISSUE TITLE
Do not expand symlink on packaged file.

### ISSUE THREAD

**Issue by rsur** [goreleaser/nfpm#183]
Per deb [specification](https://www.debian.org/doc/debian-policy/ch-files.html#symbolic-links), not only unexpanded (i.e. left as is) symlink is allowed to be shipped, it can even point to non-existent file on the source package tree, assuming the target file exists after installation. Relative symlink is strongly suggested, but absolute symlink is not entirely forbidded.

This behavior is observable on `fpm`.

So, the assertion [here](https://github.com/goreleaser/nfpm/pull/180/files#diff-363799588117b0eb7767f12380fd7afeR526) is inaccurate even though a temporary symlink is created in place of `../testdata/whatever.conf`, because it compares the content of source and packed files. It always assumes that the packed file is regular, not a symlink.

For the sake of completion, we can do tests based on this toy YAML:

```yaml
name: "some-package"
arch: "amd64"
version: "1.0.0"
files:
  ./bin/big-program: "/usr/bin/big-program"
  ./bin/sym-program: "/usr/bin/sym-program"
```

where `./bin/sym-program` is a relative symlink to `./bin/big-program`, i.e. `big-program`, hence `/usr/bin/sym-program` must also be a relative symlink to `/usr/bin/big-program`, i.e. `big-program`. We only need to ensure `/usr/bin/sym-program` has linkname `big-program` and resolve it to `/usr/bin/big-program`. We can compare the content from there on.
