### ISSUE TITLE
Multiple service with single debian package?

### ISSUE THREAD

**Issue by babu-s2** [goreleaser/nfpm#294]
⚠️ Attention points before opening the issue:

This is more of a question. I did ask the slack channel, but yet for a response.

Question is, Is there a way to install multiple services through single debian package via nfpm? If yes, please share a working example.
Thanks

Love goreleaser/nfpm? Please consider supporting our collective:

👉 https://opencollective.com/goreleaser/donate

**Comment by erikgeiser** [comment]
Like we said in the slack channel, `nfpm` can package as many services as you want to a single package. `systemd` services are just config text files at a specific location which may or may not be symlinked to other locations depending on whether they are enabled or disabled. The approach you mentioned in the slack channel is generally correct. This could be the contents of your package.

```
contents:
  - src: ./foo
    dst: /usr/local/bin/foo
  - src: ./bar
    dst: /usr/local/bin/bar
  - src: ./systemd/foo.service
    dst: /etc/systemd/system/foo.service
  - src: ./systemd/bar.service
    dst: /etc/systemd/system/bar.service
```

After installation, the services should be present on your system. They are probably not enabled, though. You can either run `systemd enable --now foo` and `systemd enable --now bar` or you could at a post install script that enables then upon installation.

If the services or one of the services do not start, it is likely due to an error in your service file or an error during runtime of your service. At this point, it has nothing to do with `nfpm` anymore, though. If you want to investigate this, you can view the service logs with `journalctl -u foo` and `journalctl -u bar`.
