### ISSUE TITLE
File Mode issue when using setuid bits

### ISSUE THREAD

**Issue by mjmjelde** [goreleaser/nfpm#392]
Howdy,

I have created an application that requires the setuid bit to be on one of the executable.  However, when I have a custom file_info mode set with the setuid bit set, it does not actually get properly set in the deb or rpm package that is created.  In fact, some weird permissions appear for the file in the deb package and the rpm package is not even able to install.

This is what I have in my nfpm.yaml file:
```
contents:
  - src: dist/myexec
    dst: /usr/local/bin/myexec
    file_info:
      mode: 4555
      owner: root
      group: root
```

But this is what permission actually show up in the package:
```
root@0db5c89952b8:/# ls -la /usr/local/bin/myexec
-rwx--x-wx. 1 root root 50326500 Nov  4 16:01 /usr/local/bin/myexec
```
