### ISSUE TITLE
Support for interpolation of environment variables in nfpm.yml

### ISSUE THREAD

**Issue by bpicode** [goreleaser/nfpm#4]
It would be nice if I could write something like
```yml
name: myapp
arch: $GOARCH
platform: $GOOS
version: 1.1.3-$CI_BUILDNUMBER
...
```
