### ISSUE TITLE
cannot unmarshal !!seq into nfpm.Overridables

### ISSUE THREAD

**Issue by suntong** [goreleaser/nfpm#416]
Adding the following lines to `yaml` file,

```yaml
overrides:
  # The depends override can for example be used to provide version constraints for dependencies where
  # different package formats use different versions or for dependencies that are named differently.
  deb:
    depends:
      - perl:any
      - curl
  rpm:
    depends:
      - perl
      - curl
  apk:
      - perl
      - curl
```

will cause the following error:

```
yaml: unmarshal errors:
  line 208: cannot unmarshal !!seq into nfpm.Overridables
```

See 
https://gist.github.com/suntong/f75115502d8f35d5576ed8685abb057e/revisions
for details. Error started from change # 3, and # 4 isn't able to fix it. 

Please double-check. 

thanks
