### ISSUE TITLE
Support tar.gz targets

### ISSUE THREAD

**Issue by xxxserxxx** [goreleaser/nfpm#461]
### Is your feature request related to a problem? Please describe.

Most of my projects provide a simple tar.gz for users to download. Currently, I write custom code for each project's CI to bundle the tarball. The information about what gets bundled into the tarball is a subset of what's specified in the NFPM file.

### Describe the solution you'd like

 I would like to be able to call `nfpm pkg --packager tarball ...` and get a zipped tarball containing the files specified in the target paths. There are a few ways the tarball could be structured, but the most straightforward would be to root the directory structure specified in the config file under `${name}/`, such that:

```yaml
name: myproject
...
contents:
  - src: mybin
    dst: /usr/local/bin/mybin
  - src: mybin.8
    dst: /usr/share/man/man8/mybin.8
```

would produce a tarball with the contents:

```
myproject/usr/local/bin/mybin
myproject/usr/share/man/man8/mybin.8
```

It'd be ideal if this were supported:

```yaml
...
contents:
  - src: mybin
    dst: mybin
    packager: tarball
  - src: mybin.8
    dst: mybin.8
    packager: tarball
  - src: install.sh
    dst: install.sh
    packager: tarball
  - src: README.md
    dst: README.md
    packager: tarball
```

with the result:

```
myproject/mybin
myproject/mybin.8
myproject/install.sh
myproject/README.md
```

### Describe alternatives you've considered

The current work-around is that, for every project, I write custom shell code to create the tarball. This precludes using (e.g.) standardized github actions for building release assets, since the list of files being included varies per project. I've considered writing my own nfpm parser to extract the information which (as I mentioned) is *already* being tracked in the `nfpm.yml` and build the tarballs that way.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Adding this support is probably within my ability, and I'm willing to give it a shot for a PR IFF -- assuming the code is acceptable -- this is a feature that might be accepted and the PR has a good chance of being merged.
