### ISSUE TITLE
Glob does not work on `archlinux` packager

### ISSUE THREAD

**Issue by j-tai** [goreleaser/nfpm#572]
### What happened?

Using a glob as a `src` file works with the `deb` packager, so it should also work with `archlinux` packager. Instead, I get

```
using archlinux packager...
stat files/*: no such file or directory
```

### How can we reproduce this?

```console
$ git clone https://github.com/j-tai/nfpm-repro
$ cd nfpm-repro
$ nfpm package -p archlinux
```

For reference, here is the `nfpm.yaml` file in that repository:

```yml
name: nfpm-repro
version: 1.0.0
maintainer: asdfasdf
contents:
  - dst: /usr/share/nfpm-repro
    src: files/*
```

### nfpm version

```bash
nfpm version nfpm version 2.21.0
commit: 50853d3ecdeeb8dbbe0c39c6ed9f6919bfe50b34
built at: 2022-10-31T14:12:51Z
built by: goreleaser
module version: v2.21.0, checksum: h1:zpj6IF8QlPuxVlrGw4F/VwG+fAWL4hjs3LQWCA4UAUs=
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
