### ISSUE TITLE
No warning/error for invalid package types

### ISSUE THREAD

**Issue by j-tai** [goreleaser/nfpm#580]
### What happened?

If you specify an invalid `type` in a package file, then that type will be silently ignored. This is confusing. Instead, nfpm should throw an error (or at least a warning).

Example scenario: the user wants to create a symlink in the package
```yaml
contents:
  - src: /usr/bin/python3
    dst: /usr/bin/python
    type: link  # oops! should be `symlink`
```
Packaging succeeds, and the user may not notice that `/usr/bin/python` is now a copy of `/usr/bin/python3` from the packaging machine, instead of a symlink.

### How can we reproduce this?

```yaml
name: foo
version: 1.2.3
prerelease: beta1
maintainer: asdf
arch: amd64
contents:
  - src: nfpm.yaml
    dst: /usr/share/nfpm.yaml
    type: asdfasdf
```

### nfpm version

```bash
nfpm version nfpm version 2.22.1
commit: 280c04f44d54f63a9c30df11899d9452a85b7d05
built at: 2022-11-17T17:49:18Z
built by: goreleaser
module version: v2.22.1, checksum: h1:S5ShUIQYIB4uUiJmBy7S0w5SvZ2CwqBOvXNvRGnO6XE=
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
