### ISSUE TITLE
.deb not creating directories for files to go in

### ISSUE THREAD

**Issue by ncw** [goreleaser/nfpm#6]
I was experimenting with nfpm for rclone...

I made a simple nfpm.yaml

```yaml
name: "rclone"
arch: "amd64"
platform: "linux"
version: "1.39"
section: "default"
priority: "extra"
provides:
- rclone
maintainer: "Nick Craig-Wood <nick@craig-wood.com>"
description: |
  Rclone "rsync for cloud storage" is a command line program to sync
    files and directories to and from most cloud providers.
vendor: "rclone"
homepage: "https://rclone.org"
license: "MIT"
bindir: "/usr/bin"
files:
  ./rclone: "/usr/bin/rclone"
  ./README.html: "/usr/share/doc/rclone/README.html"
  ./README.txt: "/usr/share/doc/rclone/README.txt"
  ./rclone.1: "/usr/share/man/man1/rclone.1"
```

Which apparently works

```
$ nfpm -f ../../nfpm.yaml pkg -t rclone.deb
using deb packager...
created package: rclone.deb
```

But when I try to install the resulting .deb I get

```
$ sudo dpkg -i ./rclone.deb 
(Reading database ... 352196 files and directories currently installed.)
Preparing to unpack ./rclone.deb ...
Unpacking rclone (1.39) ...
dpkg: error processing archive ./rclone.deb (--install):
 unable to create '/usr/share/doc/rclone/README.html.dpkg-new' (while processing '/usr/share/doc/rclone/README.html'): No such file or directory
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 ./rclone.deb
```

I'm guessing that is because the directory `'/usr/share/doc/rclone/` doesn't exist and something needs to create it.

Is that something I'm supposed to do in the config file or is it a bug?

Thanks
