### ISSUE TITLE
Symlink directory issue

### ISSUE THREAD

**Issue by mjmjelde** [goreleaser/nfpm#621]
### What happened?

When packaging directories that are symlinked to other directories, they are not included in the final package.

### How can we reproduce this?

Create some test files:
```
#!/usr/bin/env bash
mkdir testpkg
cd testpkg
mkdir -p x86_64-linux/{lib,include}
touch x86_64-linux/lib/test.txt
touch x86_64-linux/include/test.txt
ln -s x86_64-linux/lib lib
ln -s x86_64-linux/include include
```

Package them up using this as a yaml file:
```
name: "testpkg"
arch: "amd64"
platform: "linux"
version: "v1.1"
section: "default"
priority: "optional"
maintainer: "Matthew <test@email.com>"
description: |
  A test package to test a bug
vendor: "Bug hunters"
contents:
  - src: ./testpkg
    dst: /opt/testpkg
```

End up with packages containing these file:
```
$ rpm -qlp /output/testpkg-1.1.0.x86_64.rpm 
/opt/testpkg/x86_64-linux/include/test.txt
/opt/testpkg/x86_64-linux/lib/test.txt
```
or
```
$ dpkg -c output/testpkg_1.1.0_amd64.deb 
drwxr-xr-x root/root         0 2023-02-17 16:27 ./opt/
drwxr-xr-x root/root         0 2023-02-17 16:27 ./opt/testpkg/
drwxr-xr-x root/root         0 2023-02-17 16:27 ./opt/testpkg/x86_64-linux/
drwxr-xr-x root/root         0 2023-02-17 16:27 ./opt/testpkg/x86_64-linux/include/
-rw-r--r-- root/root         0 2023-02-17 16:26 ./opt/testpkg/x86_64-linux/include/test.txt
drwxr-xr-x root/root         0 2023-02-17 16:27 ./opt/testpkg/x86_64-linux/lib/
-rw-r--r-- root/root         0 2023-02-17 16:26 ./opt/testpkg/x86_64-linux/lib/test.txt
```

You notice that there are no linking files in either packages.

### nfpm version

```bash
nfpm version nfpm version 2.25.0
commit: c17fcccb1f299a90064871010eabfa95601a7326
built at: 2023-02-01T22:50:57Z
built by: goreleaser
module version: v2.25.0, checksum: h1:wDcbvH+H6Ctnr+9WBunZx/8F8SBevRDelJgwKunJADc=
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
