### ISSUE TITLE
Glob causes directory structure to be flattened

### ISSUE THREAD

**Issue by j-tai** [goreleaser/nfpm#623]
### What happened?

When you select directories using a glob, the directory structure is flattened in the resulting package. I expected it to keep the original directory structure, just like it does when you don't use a glob.

For example, in the following directory structure:
```
.
├── content/
│   ├── a/
│   │   └── b/
│   │       └── file1
│   └── x/
│       └── y/
│           └── file2
└── nfpm.yaml
```
and the following nfpm.yaml
```yaml
name: foo
arch: all
version: 1.2.3
maintainer: asdf

contents:
  - src: content/*
    dst: /usr/share/foo/
```
I expect the package to contain the files `/usr/share/foo/a/b/file1` and `/usr/share/foo/x/y/file2`. However, it actually contains `/usr/share/foo/file1` and `/usr/share/foo/file2`.

### How can we reproduce this?

```shell
git clone https://git.jtai.ca/repro/nfpm-1
cd nfpm-1
nfpm package -p archlinux
tar tf *.tar.zst
```

### nfpm version

```bash
nfpm version nfpm version 2.26.0
commit: 34276432d6614e28108b2851b298c86342c41e4c
built at: 2023-02-06T11:58:56Z
built by: goreleaser
module version: v2.26.0, checksum: h1:nL7sXwsMLsc+NWE4Eddev+ZZomRaucT0WSnWkLwuxBM=
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by erikgeiser** [comment]
I agree that this is a bit confusing, but can you explain why you would expect the package to contain `/usr/share/foo/a/b/file1` rather than `/usr/share/foo/contents/a/b/file1`?

**Comment by j-tai** [comment]
Because the behaviour should be the same as `cp`, `mv`, etc. If you want to install to `/usr/share/foo/content/a/b/file1` then you can do
```yaml
contents:
  - src: content
    dst: /usr/share/foo/content
```
