### ISSUE TITLE
master appears to have broken rpm installs on Centos 7

### ISSUE THREAD

**Issue by ncw** [goreleaser/nfpm#71]
A user reported that the latest rpm builds aren't working for rclone: https://github.com/rclone/rclone/issues/3580

This turns out to be because I accidentally set the CI to use the master branch of nfpm.

I thought you might like to hear about this anyway though...

So using a single binary `rclone` and the slightly edited template

```yaml
# nfpm example config file
name: "foo"
arch: "amd64"
platform: "linux"
version: "v1.49.4-test"
section: "default"
priority: "extra"
replaces:
- foobar
provides:
- bar
depends:
- foo
- bar
# recommends on rpm packages requires rpmbuild >= 4.13
recommends:
- whatever
# suggests on rpm packages requires rpmbuild >= 4.13
suggests:
- something-else
conflicts:
- not-foo
- not-bar
maintainer: "John Doe <john@example.com>"
description: |
  FooBar is the great foo and bar software.
    And this can be in multiple lines!
vendor: "FooBarCorp"
homepage: "http://eaxmple.com"
license: "MIT"
bindir: "/usr/local/bin"
files:
  ./rclone: "/usr/local/bin/rclone"
```

I create the `.rpm` file with

```
nfpm pkg --target fake.rpm
```

On a Centos 7 machine I can then look at the rpms...

# rpm created with nftp 0.13

```
$ rpm -qp --info fake.rpm
Name        : foo
Version     : 1.49.4_test
Release     : 1
Architecture: x86_64
Install Date: (not installed)
Group       : Development/Tools
Size        : 42949808
License     : MIT
Signature   : (none)
Source RPM  : foo-1.49.4_test-1.src.rpm
Build Date  : Tue 01 Oct 2019 12:34:41 UTC
Build Host  : dogger
Relocations : (not relocatable)
Packager    : John Doe <john@example.com>
URL         : http://eaxmple.com
Summary     : FooBar is the great foo and bar software.
Description :
FooBar is the great foo and bar software.
  And this can be in multiple lines!
```

Installs fine

```
$ sudo rpm -i fake.rpm 
$
```

# rpm created with nfpm master

```
$ rpm -qp --info fake.rpm
Name        : foo
Version     : 1.49.4-test
Release     : 
Architecture: x86_64
Install Date: (not installed)
Group       : (none)
Size        : 42949808
License     : 
Signature   : (none)
Source RPM  : foo-1.49.4-test.src.rpm
Build Date  : (none)
Build Host  : (none)
Relocations : (not relocatable)
Packager    : 
Vendor      : 
URL         : 
Summary     : (none)
Description :
(none)
```

Fails to install

```
$ sudo rpm -i fake.rpm 
	package foo-1.49.4-test-.x86_64 is intended for a different operating system
$
```
