### ISSUE TITLE
Ability to specify a type as "config|tree" for `/etc` so that all files are referenced in configfiles

### ISSUE THREAD

**Issue by acabarbaye** [goreleaser/nfpm#769]
### Is your feature request related to a problem? Please describe.

currently, `config` type seems to only apply to individual files and according to schema cannot be used in addition to the `tree` type.

### Describe the solution you'd like

the solution would be to introduce a new type `config|tree` which would combine the behaviour of each type: reproduce the tree structure and mark each files found as configuration file

### Describe alternatives you've considered

the only alternative is to do this manually and reference every file as "config". 

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ursetto** [comment]
Just want to note that `config|noreplace` is practically required for RPM packages -- `fpm` defaults to `%config(noreplace)` for all RPM config files -- and so ideally should be supported with this new `config|tree` option. But since these are types (not flags) under the current implementation, that would result in a combinatorial explosion of types like `config|tree|noreplace`.

**Comment by djgilcrease** [comment]
can you test with #1104 and see if this behaves like you want

```yaml
  # Like 'tree', but every regular file discovered while walking the directory
  # is also marked as a config file (equivalent to setting 'type: config' on
  # each of them). Directories and symlinks keep their natural type.
  # 'config|noreplace|tree' and 'config|missingok|tree' behave the same but mark
  # the files with the respective RPM directive.
  - src: some/config-directory/
    dst: /etc/myapp
    type: config|tree
```
