### ISSUE TITLE
Issue dealing with "hidden" files starting with `.`

### ISSUE THREAD

**Issue by acabarbaye** [goreleaser/nfpm#857]
### What happened?

We are getting errors when trying to package files with a leading `.` in their names
e.g.
```
 matching "./.env.docker-compose-acceptancetests": file does not exist
 ```

### How can we reproduce this?

trying to have a source file in `src` with a name starting with `.` such as `.env`

### nfpm version

```bash
version 2.40.0
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
tried this example:

```yaml
# This is an example nfpm configuration file.
# Make sure to check the documentation at https://nfpm.goreleaser.com
#
# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://nfpm.goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

name: "foo"
arch: "amd64"
platform: "linux"
version: "1.0.0"
section: "default"
priority: "extra"
maintainer: "John Doe <john@example.com>"
description: |
  FooBar is the great foo and bar software.
    And this can be in multiple lines!
vendor: "FooBarCorp"
homepage: "http://example.com"
license: "MIT"
contents:
  - src: ./.gitignore
    dst: /tmp/gitignore
```

works as expected.

please provide a minimal reproducible.
