### ISSUE TITLE
/etc/default for Debian vs /etc/sysconfig for RPM

### ISSUE THREAD

**Issue by franchb** [goreleaser/nfpm#879]
### Is your feature request related to a problem? Please describe.

In both Debian and RPM-based systems, the directories `/etc/default` and `/etc/sysconfig` are used to store configuration files for system services, but there are some differences in their usage and conventions:
### Debian (`/etc/default`)
- **Location**: Configuration files for services in Debian-based systems are typically found in the `/etc/default` directory.
- **Purpose**: The files within this directory typically contain environment variables that are utilized by the service startup scripts located in `/etc/init.d` or `/lib/systemd/system`.
- **Example**: A configuration file for `cron` on a Debian-based system might be `/etc/default/cron`.
### RPM-Based (`/etc/sysconfig`)
- **Location**: In RPM-based distributions configuration files for services are usually placed in the `/etc/sysconfig` directory.
- **Purpose**: These files serve a similar purpose to those in Debian's `/etc/default`, containing environment variables for service startup scripts located in `/etc/init.d` or systemd unit files.
- **Example**: A configuration file for the network service might be `/etc/sysconfig/network`.
### Key Points:
1. **Function**: Both directories serve the function of providing configurable parameters for services and daemons. The variables defined here are typically sourced by service start scripts or systemd unit files.
2. **Standardization**: While `/etc/default` is standard for Debian-based distributions, `/etc/sysconfig` is the norm for RPM-based distributions.
3. **Environment Variables**: These files generally define environment variables that dictate how services start, with parameters such as command-line options, paths, and other runtime configurations.
#### Debian (`/etc/default/nginx`):
```sh
# Run NGINX with this user
NGINX_USER=www-data
# Run NGINX with these options
NGINX_OPTS=""
```
#### RPM-Based (`/etc/sysconfig/nginx`):
```sh
# Options to pass to nginx
NGINX_OPTS="-c /etc/nginx/nginx.conf"
```
Both approaches allow system administrators to control service behaviors without modifying the main startup scripts, promoting modular and maintainable configurations.

### Describe the solution you'd like

A method to provide environment variables to a service in a generic way for both Debian and RPM-based distributions.

### Describe alternatives you've considered

Copy `.env` file to both locations

```yaml
  - src: {{.Paths.EnvFile}}
    dst: /etc/default/{{.Name}} # for DEB-based
    type: config|noreplace

  - src: {{.Paths.EnvFile}}
    dst: /etc/sysconfig/{{.Name}}  # for RPM-based
    type: config|noreplace
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
hey!

you should be able to:

```yaml

  - src: {{.Paths.EnvFile}}
    dst: /etc/default/{{.Name}} # for DEB-based
    type: config|noreplace
    packager: deb

  - src: {{.Paths.EnvFile}}
    dst: /etc/sysconfig/{{.Name}}  # for RPM-based
    type: config|noreplace
```
